// <auto-generated />
using CloneRozetka.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloneRozetka.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225120000_AddCompareItems")]
    partial class AddCompareItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is reflected in AppDbContextModelSnapshot after this migration.
        }
    }
}
